#ifndef PNPIPCINC_H
#define PNPIPCINC_H

#define MODULE_NAME "pnpipcinc"

enum {
	FREQUENCY_1MHZ,
	FREQUENCY_500KHZ,
	FREQUENCY_250KHZ,
	FREQUENCY_125KHZ,
	FREQUENCY_100KHZ,
	FREQUENCY_50KHZ,
	FREQUENCY_25KHZ,
	FREQUENCY_12500HZ,
};

#define GATE_ON 64
#define TIMER_ON 32
#define INVERTED_ON 16
#define EXTERNAL_FREQUENCY 8
#define IOCTL_CMD_SET_LEADING_COUNTER 128

#endif
