#ifndef PNPIPCINC_H
#define PNPIPCINC_H

#define MODULE_NAME "pnpipcinc"

enum {
	FREQUENCY_1MHZ,
	FREQUENCY_500KHZ,
	FREQUENCY_250KHZ,
	FREQUENCY_125KHZ,
	FREQUENCY_100KHZ,
	FREQUENCY_50KHZ,
	FREQUENCY_25KHZ,
	FREQUENCY_12500HZ,
};

#define CS0_ADDR_OFFSET_LEADING_AND_TOF 0
#define CS0_ADDR_OFFSET_INVERTED 1
#define CS0_ADDR_OFFSET_FLUSH 2

/* TV */
#define CS2_ADDR_OFFSET_FREQUENCY_AND_PARAMETERS 4
#define CS2_ADDR_OFFSET_CLEAR_START_COUNTER 5
#define CS2_ADDR_OFFSET_READ_WRITE_COUNTER 6
#define CS2_ADDR_OFFSET_READ_SET_COUNTER 10

/* Madlen
#define CS2_ADDR_OFFSET_FREQUENCY_AND_PARAMETERS 9
#define CS2_ADDR_OFFSET_CLEAR_START_COUNTER 10
#define CS2_ADDR_OFFSET_READ_WRITE_COUNTER 11
#define CS2_ADDR_OFFSET_READ_SET_COUNTER 15
*/

enum {
	IOCTL_CMD_REG_FREQUENCY,
	IOCTL_CMD_CLEAR_AND_START_COUNTER,
	IOCTL_CMD_LEAD_COUNTER_AND_TOF,
	IOCTL_CMD_INVERSE_SIGNAL,
	IOCTL_CMD_FORBID_ALLOW_CLEAR_COUNTER
};


#define GATE_ON 64
#define TIMER_ON 32
#define INVERTED_ON 16
#define EXTERNAL_FREQUENCY 8

#define CLEAR_COUNT 1
#define START_COUNT 2 
#define CLEAR_REG_COUNT 4
#define ENABLE_FREQUENCY_COUNT 8
#endif
